version: "3"
services: 
  pg:
    image: postgres:16
    restart: always
    hostname: pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jms
    ports:
      - "5432:5432"
    volumes:
      - /root/data:/var/lib/postgresql/data

  jms-sshd:
    depends_on:
      - pg
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "22222:22222"
    environment:
      - TIMEOUT=1800
      - DEBUG=false
    volumes: 
      - "/opt/jms/config.yaml:/opt/jms/config.yaml"
      - "/opt/jms/:/opt/jms/"

  jms-scheduler:
    depends_on:
      - pg
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "6060:6060"
    environment:
      - DEBUG=false
      - SCHEDULER=true
    volumes:
      - "/opt/jms/config.yaml:/opt/jms/config.yaml"

  jms-api:
    depends_on:
      - pg
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8013:8013"
    environment:
      - DEBUG=false
      - API=true
    volumes: 
      - "/opt/jms/config.yaml:/opt/jms/config.yaml"