// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/approval": {
            "post": {
                "description": "创建策略",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Approval"
                ],
                "summary": "创建审批策略",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ApprovalMut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/approval/:id": {
            "patch": {
                "description": "更新审批结果，可以是同意或者拒绝",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Approval"
                ],
                "summary": "更新审批",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "approval id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ApprovalResult"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/audit/login": {
            "get": {
                "description": "服务器登录审计查询，支持查询用户、IP、时间范围的日志",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "listLoginAudit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "days",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ip",
                        "name": "ip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "user",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SSHLoginRecord"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/audit/scp": {
            "get": {
                "description": "服务器文件上传下载审计查询，支持上传upload,下载 download，文件名，服务器IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "listScpAudit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "days",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "action",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "user",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ScpRecord"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/broadcast": {
            "post": {
                "description": "broadcast",
                "consumes": [
                    "application/json"
                ],
                "summary": "Broadcast",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateBroadcastRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/key": {
            "get": {
                "description": "列出密钥，数据隐藏",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "列出密钥",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Key"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "添加密钥",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "添加密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "key",
                        "name": "key",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/key/:uuid": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "删除密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "key uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "登录接口可以换token使用。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "user",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/policy": {
            "get": {
                "description": "获取策略列表，只能查某人或者某个组或者某个策略，不可组合查询，查用户会带出用户所在组的策略",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "获取策略列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "policy id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "user",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Policy"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/policy/:id": {
            "put": {
                "description": "更新策略",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "更新策略",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "policy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除策略",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "删除策略",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "policy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "List profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Profile"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Create profile",
                "parameters": [
                    {
                        "description": "profile",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/profile/:uuid": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update profile",
                "parameters": [
                    {
                        "description": "profile",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateProfileRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "profile uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Delete profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "profile uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy": {
            "get": {
                "description": "list proxy servers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "ListProxy",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Proxy"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "add proxy server",
                "tags": [
                    "proxy"
                ],
                "summary": "AddProxy",
                "parameters": [
                    {
                        "description": "proxy server info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Proxy"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/:uuid": {
            "put": {
                "tags": [
                    "proxy"
                ],
                "summary": "UpdateProxy",
                "parameters": [
                    {
                        "description": "proxy server info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateProxyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "proxy server uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Proxy"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "DeleteProxy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "proxy server uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/shell/record": {
            "get": {
                "description": "list shell record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shell"
                ],
                "summary": "ListShellRecord",
                "parameters": [
                    {
                        "type": "string",
                        "description": "taskid",
                        "name": "taskid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "serverip",
                        "name": "serverip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ShellTaskRecord"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/shell/task": {
            "get": {
                "description": "list shell tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shell"
                ],
                "summary": "ListShellTask",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ShellTask"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "add shell task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shell"
                ],
                "summary": "AddShellTask",
                "parameters": [
                    {
                        "description": "shell",
                        "name": "shell",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateShellTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/shell/task/:uuid": {
            "put": {
                "description": "update shell task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shell"
                ],
                "summary": "UpdateShellTask",
                "parameters": [
                    {
                        "description": "shell",
                        "name": "shell",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateShellTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete shell task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shell"
                ],
                "summary": "DeleteShellTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "shell task uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "description": "获取用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "name 支持用户名或者email查询",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "添加用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "添加用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/:id": {
            "put": {
                "description": "更新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "支持数组会与现有组进行合并",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "追加用户组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserPatchMut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "model.Action": {
            "type": "string",
            "enum": [
                "connect",
                "deny_connect",
                "download",
                "deny_download",
                "upload",
                "deny_upload"
            ],
            "x-enum-varnames": [
                "Connect",
                "DenyConnect",
                "Download",
                "DenyDownload",
                "Upload",
                "DenyUpload"
            ]
        },
        "model.AddKeyRequest": {
            "type": "object",
            "required": [
                "key_id",
                "pem_base64"
            ],
            "properties": {
                "identity_file": {
                    "description": "云上下载下来的名字，比如 jms-key.pem，private key file name",
                    "type": "string"
                },
                "key_id": {
                    "description": "云上的key id，比如 skey-123456",
                    "type": "string"
                },
                "pem_base64": {
                    "description": "base64",
                    "type": "string"
                },
                "profile": {
                    "description": "云账号的 profile，比如 aws, aliyun",
                    "type": "string"
                }
            }
        },
        "model.ApprovalMut": {
            "type": "object",
            "required": [
                "applicant",
                "server_filter",
                "users"
            ],
            "properties": {
                "actions": {
                    "description": "申请动作，默认只有connect",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Action"
                    }
                },
                "applicant": {
                    "description": "申请人AD名,或者email",
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "description": "审批周期，默认一周",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Period"
                        }
                    ]
                },
                "server_filter": {
                    "$ref": "#/definitions/model.ServerFilterV1"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ApprovalResult": {
            "type": "object",
            "properties": {
                "applicant": {
                    "type": "string"
                },
                "is_pass": {
                    "type": "boolean"
                }
            }
        },
        "model.CreateBroadcastRequest": {
            "type": "object",
            "required": [
                "messages"
            ],
            "properties": {
                "keepDays": {
                    "description": "保留天数，0 表示永久",
                    "type": "integer"
                },
                "messages": {
                    "description": "消息内容",
                    "type": "string"
                }
            }
        },
        "model.CreateProfileRequest": {
            "type": "object",
            "properties": {
                "ak": {
                    "type": "string"
                },
                "cloud": {
                    "description": "aws, aliyun, tencent",
                    "type": "string",
                    "default": "tencent"
                },
                "enabled": {
                    "description": "是否启用",
                    "type": "boolean",
                    "default": true
                },
                "name": {
                    "type": "string"
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sk": {
                    "type": "string"
                }
            }
        },
        "model.CreateProxyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "identity_file": {
                    "description": "KeyID和IdentityFile都是用pem来验证，KeyID是唯一的，IdentityFile在名称命名时候不同账号可能会同名。当出现IdentityFile不唯一的时候可以用 keyID, 优先使用KeyID",
                    "type": "string"
                },
                "ip_prefix": {
                    "description": "适配哪些机器 IP 前缀使用 Proxy, 例如 192.168.1",
                    "type": "string"
                },
                "key_id": {
                    "description": "KeyID和IdentityFile都是用pem来验证，KeyID是唯一的，IdentityFile在名称命名时候不同账号可能会同名。当出现IdentityFile不唯一的时候可以用 keyID, 优先使用KeyID",
                    "type": "string"
                },
                "login_passwd": {
                    "description": "密码或者key必须有一个, 优先使用密码",
                    "type": "string"
                },
                "login_user": {
                    "description": "key超级用户 root ec2-user",
                    "type": "string"
                },
                "name": {
                    "description": "代理名称 唯一",
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                }
            }
        },
        "model.CreateShellTaskRequest": {
            "type": "object",
            "required": [
                "name",
                "servers",
                "shell"
            ],
            "properties": {
                "corn": {
                    "description": "corn表达式，支持定时执行任务，执行一次可以不传",
                    "type": "string"
                },
                "name": {
                    "description": "任务名称，唯一",
                    "type": "string"
                },
                "servers": {
                    "description": "执行的机器",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.ServerFilterV1"
                        }
                    ]
                },
                "shell": {
                    "description": "脚本内容",
                    "type": "string"
                }
            }
        },
        "model.Key": {
            "type": "object",
            "properties": {
                "isDelete": {
                    "type": "boolean"
                },
                "keyID": {
                    "type": "string"
                },
                "keyName": {
                    "type": "string"
                },
                "pemBase64": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.Period": {
            "type": "string",
            "enum": [
                "1d",
                "1w",
                "1m",
                "1y",
                "ever"
            ],
            "x-enum-varnames": [
                "OneDay",
                "OneWeek",
                "OneMonth",
                "OneYear",
                "Forever"
            ]
        },
        "model.Policy": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "approval_id": {
                    "description": "审批ID",
                    "type": "string"
                },
                "approver": {
                    "description": "审批人",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "server_filter": {
                    "$ref": "#/definitions/model.ServerFilter"
                },
                "server_filter_v1": {
                    "$ref": "#/definitions/model.ServerFilterV1"
                },
                "updated_at": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.PolicyRequest": {
            "type": "object",
            "required": [
                "name",
                "server_filter"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expires_at": {
                    "type": "string"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "server_filter": {
                    "$ref": "#/definitions/model.ServerFilterV1"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Profile": {
            "type": "object",
            "properties": {
                "ak": {
                    "type": "string"
                },
                "cloud": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sk": {
                    "description": "经过加密",
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.Proxy": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "identityFile": {
                    "type": "string"
                },
                "ipprefix": {
                    "type": "string"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "keyID": {
                    "type": "string"
                },
                "loginPasswd": {
                    "type": "string"
                },
                "loginUser": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.SSHLoginRecord": {
            "type": "object",
            "properties": {
                "client": {
                    "description": "客户端",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "target": {
                    "description": "目标服务器",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "description": "用户",
                    "type": "string"
                }
            }
        },
        "model.ScpRecord": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "download,upload",
                    "type": "string"
                },
                "client": {
                    "description": "客户端",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "from": {
                    "description": "来源",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "to": {
                    "description": "目标",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "description": "用户",
                    "type": "string"
                }
            }
        },
        "model.ServerFilter": {
            "type": "object",
            "properties": {
                "env_type": {
                    "description": "机器 Tags 中的 EnvType，支持* 匹配所有",
                    "type": "string"
                },
                "ip_addr": {
                    "description": "IP 地址完全匹配，支持* 匹配所有",
                    "type": "string"
                },
                "name": {
                    "description": "名字完全匹配，支持*",
                    "type": "string"
                },
                "team": {
                    "description": "机器 Tags 中的 Team，支持* 匹配所有",
                    "type": "string"
                }
            }
        },
        "model.ServerFilterV1": {
            "type": "object",
            "properties": {
                "env_type": {
                    "description": "机器 Tags 中的 EnvType，支持* 匹配所有",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ip_addr": {
                    "description": "IP 地址完全匹配，支持* 匹配所有",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "名字完全匹配，支持*",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "team": {
                    "description": "机器 Tags 中的 Team，支持* 匹配所有",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ShellTask": {
            "type": "object",
            "properties": {
                "corn": {
                    "type": "string"
                },
                "cost_time": {
                    "type": "integer"
                },
                "exec_result": {
                    "description": "任务执行结果信息",
                    "type": "string"
                },
                "exec_times": {
                    "description": "任务执行次数",
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "servers": {
                    "$ref": "#/definitions/model.ServerFilterV1"
                },
                "shell": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.Status"
                },
                "submit_user": {
                    "description": "直接在token中获取",
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.ShellTaskRecord": {
            "type": "object",
            "properties": {
                "cost_time": {
                    "type": "string"
                },
                "exec_times": {
                    "type": "integer"
                },
                "is_success": {
                    "type": "boolean"
                },
                "output": {
                    "type": "string"
                },
                "server_ip": {
                    "type": "string"
                },
                "server_name": {
                    "type": "string"
                },
                "shell": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.Status": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Success",
                "Failed",
                "NotAllSuccess",
                "Cancelled"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusRunning",
                "StatusSuccess",
                "StatusFailed",
                "StatusNotAllSuccess",
                "StatusCancelled"
            ]
        },
        "model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "dingtalk_dept_id": {
                    "type": "string"
                },
                "dingtalk_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "groups": {
                    "description": "组不在 jms维护这里只需要和机器 tag:Team 匹配即可。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "is_ldap": {
                    "type": "boolean"
                },
                "passwd": {
                    "description": "bas64",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserPatchMut": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.UserRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "dingtalk_dept_id": {
                    "type": "string"
                },
                "dingtalk_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "passwd": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "localhost:8013",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "cbs manager API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
